--PORTFOLIO PROJECT

SELECT * FROM coviddeaths$
WHERE continent IS NOT NULL
ORDER BY 3,4

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, POPULATION 
FROM coviddeaths$

--LOOKING AT TOTAL CASES VS TOTAL DEATHS

SELECT LOCATION, DATE, TOTAL_CASES, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE 
FROM coviddeaths$
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1, 2

--LOOKING AT TOTAL CASES VS POPULATION
-- SHOWS WHAT PERCETAGE OF POPULATION GOT COVID

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION, (TOTAL_CASES/POPULATION)*100 AS DEATHPERCENTAGE 
FROM coviddeaths$
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1, 2

--LOOKING AT COUNTRIES WITH THE HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, (MAX(TOTAL_CASES/POPULATION))*100 AS PERCENTPOPINFECTED
FROM coviddeaths$
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPINFECTED DESC

--SHOWING COUNTRYS WITH HIGHEST DEATH COUNT PER POPULATION 

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM coviddeaths$
WHERE continent IS NOT NULL
GROUP BY LOCATION 
ORDER BY TOTALDEATHCOUNT DESC

--SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT location, MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM coviddeaths$
WHERE continent IS NULL
GROUP BY location 
ORDER BY TOTALDEATHCOUNT DESC 

-- GLOBAL NUMBEERS

SELECT DATE, SUM(NEW_CASES) AS TOTALCASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTALDEATHS, 
SUM(CAST (NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM coviddeaths$
WHERE CONTINENT IS NOT NULL
GROUP BY date
ORDER BY 1, 2

--LOOKING AT TOTALPOPULATION VS VACINATIONS

SELECT coviddeaths$.continent, coviddeaths$.location, coviddeaths$.date, coviddeaths$.population, 
covidvaccinations$.new_vaccinations, 
SUM(CAST(covidvaccinations$.new_vaccinations AS BIGINT)) OVER (PARTITION BY coviddeaths$.location ORDER BY Coviddeaths$.LOCATION,
Coviddeaths$.DATE) AS ROLLINGVACCINATION
FROM coviddeaths$
JOIN covidvaccinations$
ON coviddeaths$.LOCATION =covidvaccinations$.LOCATION
AND coviddeaths$.DATE= covidvaccinations$.DATE
WHERE coviddeaths$.continent IS NOT NULL
ORDER BY 2,3

--CTE

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGVACCINATION)
AS
(
SELECT coviddeaths$.continent, coviddeaths$.location, coviddeaths$.date, coviddeaths$.population, 
covidvaccinations$.new_vaccinations, 
SUM(CAST(covidvaccinations$.new_vaccinations AS BIGINT)) OVER (PARTITION BY coviddeaths$.location ORDER BY Coviddeaths$.LOCATION,
Coviddeaths$.DATE) AS ROLLINGVACCINATION
FROM coviddeaths$
JOIN covidvaccinations$
ON coviddeaths$.LOCATION =covidvaccinations$.LOCATION
AND coviddeaths$.DATE= covidvaccinations$.DATE
WHERE coviddeaths$.continent IS NOT NULL
--ORDER BY 2,3
)
SELECT *, (ROLLINGVACCINATION/POPULATION)*100
FROM POPVSVAC

-- CREATEING VIEW TO STORE DATE LATER TABLEAU

CREATE VIEW ROLLINGVACCINATION AS 
SELECT coviddeaths$.continent, coviddeaths$.location, coviddeaths$.date, coviddeaths$.population, 
covidvaccinations$.new_vaccinations, 
SUM(CAST(covidvaccinations$.new_vaccinations AS BIGINT)) OVER (PARTITION BY coviddeaths$.location ORDER BY Coviddeaths$.LOCATION,
Coviddeaths$.DATE) AS ROLLINGVACCINATION
FROM coviddeaths$
JOIN covidvaccinations$
ON coviddeaths$.LOCATION =covidvaccinations$.LOCATION
AND coviddeaths$.DATE= covidvaccinations$.DATE
WHERE coviddeaths$.continent IS NOT NULL
--ORDER BY 2,3

